### ISSUE TITLE
Scissor Test support

### ISSUE THREAD

**Issue by leixng** [oframe/ogl#109]
Hi
First of all thank you for the library. Love using it!

If I'm not mistaken,  scissor test & custom viewport are not currently supported by OGL. 
Are those things that you would consider to be supported by the library ? 

I currently have a pretty simple use case where I want to display multiple scenes on a single canvas, and I thought having a method similar to Three.js' `setScissor` could come handy alongside  with `x` & `y`  support on `setViewport` method.

And it probably would make things easier for VR related needs ( #77  ) 

What do you think ? :)

**Comment by gordonnl** [comment]
Hey, thanks a lot!

I'm definitely up for considering scissor test support, however I'm not currently familiar with all of the steps needed to achieve what you're after.

Looking at the docs https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/scissor it seems like it's only a couple of lines needed (enable, then define the section within the viewport), so I currently can't imagine how a helper class could make this any simpler.

Could you please have a look at using these native methods in conjunction with the OGL render method?

For the VR needs, it's a little more involved as it requires rendering the same scene with a slight offset, so there are important optimisations to be made, for example so that it renders each object to both eyes one by one, rather than rendering the whole scene and then starting from scratch for the second eye. This is why I recommend in that task to create a separate VR class that overrides the render method.

**Comment by leixng** [comment]
Hey @gordonnl 
Thanks for answering so quickly! 🙏 

So in my case I indeed only needed to do something like
`gl.enable(gl.SCISSOR_TEST);
gl.viewport(left, bottom, width, height); 
gl.scissor(left, bottom, width, height);

renderer.render({scene, camera})`


And it worked!
Thanks to the fact you're caching the viewport values in the [setViewport method] (https://github.com/oframe/ogl/blob/dac670f2357ca1257cad3184f9472cbbafa047a9/src/core/Renderer.js#L122), I was able to override the viewport size by directly calling the native method like above. 

I'm aware that my usecase is pretty specific but maybe it would be nice for the `setViewport` method to accept `x` & `y` values? Even though calling the native one is definitely not some hard task, but since the OGL method exist, might as well for it to handle those ?

**Comment by leixng** [comment]
Actually I believe even a `setScissor`  in the OGL Renderer would come handy so that it always matches the DPR too

**Comment by gordonnl** [comment]
Nice!
Sounds absolutely reasonable for adding optional `x, y` to the `setViewport` method.

For `setScissor`, do you think you would want it to calculate DPR for you?

**Comment by leixng** [comment]
Sorry for the delay!

At first I thought `setViewport` was already handling the DPR, like the way Three.js works
But then I realized that it's not explicitly the case in OGL haha So what I meant really is that if we end up adding a `setScissor` method, it should be consistent with the way `setViewport` work as they would accept the same`x, y, width, height` params. So if ones calculate calculates the DPR, the other should too.

Is there a lot of use case where setViewport doesn't need to be DPR dependent ? Except for render targets of course
Because in my experience I almost always want it to be DPR dependent, which lead me to believe that both of these 2 methods should be aware of the DPR (with maybe a optional param to disable it if necessary ?)

**Comment by eXponenta** [comment]
I think that GL context must be DPR independent, because DPR applied on canvas element and not used inside GL context.
