### ISSUE TITLE
Flowmap in MSDF Text

### ISSUE THREAD

**Issue by karlos8** [oframe/ogl#118]
Hi, I'm new to the Webgl, so please be kind.
I have created a canvas scene with  MSDF Text like in your examples and I would like to add a mouse flowmap distortion on them. 
The mouse flowmap from the example has a Texture image in order to work... Is it possible instead of a Texture Image to achieve the effect in MSDF Texts?

Thanks in advance

**Comment by gordonnl** [comment]
Hi @karlos8,

Yes the effect is possible, but probably not in the way you're currently thinking!
In order to achieve this effect, the easiest way would be to: 
 - Render your MSDF text scene to a texture (see [this example](https://oframe.github.io/ogl/examples/?src=render-to-texture.html))
 - Then pass that rendered-texture in as the input to the Mouse Flowmap example!
 
 I hope that helps!

**Comment by karlos8** [comment]
Thanks for the quick response 😉
