### ISSUE TITLE
Add attributes to vertex shaders

### ISSUE THREAD

**Issue by kekkorider** [oframe/ogl#21]
Does OGL provide a way to add them or I have to do it _"the WebGL way"_? 🤔

**Comment by gordonnl** [comment]
OGL makes it easier, but it's a very light abstraction. You do so using the Geometry class.

```
const geometry = new Geometry(gl, {
    position: {size: 2, data: new Float32Array([-1, -1, 3, -1, -1, 3])},
    uv: {size: 2, data: new Float32Array([0, 0, 2, 0, 0, 2])},
});
```
The above (taken from the [triangle example](https://github.com/oframe/ogl/blob/master/examples/triangle-screen-shader.html)) uses the ```addAttribute``` method internally, but if need be you can also add attributes after initialisation:
```
const geometry = new Geometry(gl);
geometry.addAttribute('position', {size: 2, data: new Float32Array([-1, -1, 3, -1, -1, 3])});
```
The following breakdown is taken from the [Geometry class](https://github.com/oframe/ogl/blob/master/src/core/Geometry.js)
```
// attribute params
// {
//     data - typed array eg UInt16Array for indices, Float32Array
//     size - int default 1
//     instanced - default null. Pass divisor amount
//     type - gl enum default gl.UNSIGNED_SHORT for 'index', gl.FLOAT for others
//     normalize - boolean default false
// }
```
It makes dealing with attributes fairly straight forward, for example the [example of instancing](https://github.com/oframe/ogl/blob/master/examples/instancing.html) shows how to instance a geometry by just adding an instanced attribute.

The main disclaimer is that if you want to add indices (see [indexed vs non-indexed example](https://github.com/oframe/ogl/blob/master/examples/indexed-vs-non-indexed.html)), you need to use the name 'index'. Otherwise you're not forced to use any naming conventions.
