### ISSUE TITLE
jsdoc

### ISSUE THREAD

**Issue by eXponenta** [oframe/ogl#28]
Why ogl does not has JSDoc for type checking and intelisense?

I can do it, because i use TS and currently OGL unusable for me.

**Comment by jniac** [comment]
I'm not the author, but i guess it's because it take time to document every single function. Actually the code is quite clear and is very readable (eg [Camera.js](https://github.com/oframe/ogl/blob/master/src/core/Camera.js)). 

It's not the purpose i know, but i would like to point out the fact that this kind of readable source code is a good way for me to learn how to write engine. So thank you for sharing.

**Comment by gordonnl** [comment]
Thanks for the question, and thanks @jniac for the response!

@eXponenta have you seen [this other issue, in which a fellow typescripter has generated definitions](https://github.com/oframe/ogl/issues/24#issuecomment-543780060)? I don't think it helps with type information, but I believe it should make the library usable for you for now.

For JSDocs, @jniac is correct in that I wanted to keep the source code digestible. In some cases, adding jSDocs would double the amount of code. Another reason is that it would be another undertaking to include them, and keep them updated - hence slowing down progress on new features.
