### ISSUE TITLE
[Question] Run shadertoy shaders with ogl

### ISSUE THREAD

**Issue by Jones-S** [oframe/ogl#31]
Hi there
I am quite new to webgl so please apologize for any stupid question I might ask...

I am currently trying to run a shader from Shadertoy (https://www.shadertoy.com/view/4sdXDl) with ogl.
I thought I would just have to use the vertexShader and the fragmentShader, which are defined there and pass them with some uniforms into a new Program.

This is what I tried, but I would get this error
> TypeError: this.uniformLocations is undefined

And following the stack trace I end up here:
https://github.com/oframe/ogl/blob/f7f360b7bdb17424df5474847f7a962786964413/src/core/Program.js#L80

I first thought it was because I was not passing in every uniform, but even with defining all of them:
```
    // just taking random values 🤷‍♂️
    const uniforms = {
      iGlobalTime: { value: 1.0 },
      iChannelTime: { value: 1.0 },
      iMouse: { value: new Vec4(1, 1, 1, 1)},
      iDate: { value: new Vec4(1, 1, 1, 1)},
      iSampleRate: { value: 1.0 },
      iChannelResolution: new Vec3(100, 100, 0),
      iFrame: { value: 1 },
      iTimeDelta: { value: 1.0 },
      iFrameRate: { value: 1.0 }
    }
```

I know the examples are nicely structured, but in comparison to an oldschool documentation I don't really know where to start looking.
Maybe you could point me into the right direction?
Huge thanks in advance. Cheers

Ah, and of course: my current standing:
https://github.com/Jones-S/sound-machine/blob/16e655534972127cb879bbddcc6d7498065e3e72/src/components/PulsingSphere/PulsingSphere.svelte

--- Edit:
And some of the code I got from this post:
https://stackoverflow.com/a/36994606/1121268
Where somebody wanted to run a shaderToy Shader in three js. That's where I copied the fragmentShader definition...

**Comment by eXponenta** [comment]
![image](https://user-images.githubusercontent.com/12572222/68543575-d2502900-03c9-11ea-9745-ffc8f8d55c04.png)

**Comment by Jones-S** [comment]
Thanks for the hint. 🙈 
But: I changed it but it would not solve the problem...

**Comment by eXponenta** [comment]
It is not so easy. 
There sintacsical differenve between **glsl 100** and **glsl 300 es**.
You use and 100 and 300. 
userShader is glsl 100, fragmentShader is 300 es. 300 works only on WebGL2

**Comment by Jones-S** [comment]
Oh ok. I guess that means I have to go back to basic... 😓 
Thanks anyway...

**Comment by eXponenta** [comment]
@Jones-S I can help you with it if you create public fiddle on codepen or codesandbox.

**Comment by Jones-S** [comment]
That would be awesome. I will start right away and get back to you.
Hey, very much appreciated!!!

**Comment by Jones-S** [comment]
Ok, I created a codepen:
https://codepen.io/jones-s/pen/KKKBpdp
As you can see in the console, I get this error mentioned before.

I also found this:
https://github.com/Jam3/glsl-100-to-300/
Would this might help to rewrite the shaders?

**Comment by Jones-S** [comment]
Also I found out that somehow shadertoy provides (or at least provided in the past) some boilerplate code:
http://viclw17.github.io/2018/06/12/GLSL-Practice-With-Shadertoy/

Which I included from the stackoverflow link.
When googling I can't find an official shadertoy page providing this example, but that boilerplate is my `fragmentShader`

**Comment by gordonnl** [comment]
Hey, I think this might be a good example to include. It's quite often that people want to explore and expand-upon Shadertoy shaders. 

This is a good intro into what is involved: https://threejsfundamentals.org/threejs/lessons/threejs-shadertoy.html

There are a couple of challenging parts, such as recreating all of the uniforms so that they behave identically to the Shadertoy app, and editing the shaders for the different platforms' support (if you want to support both WebGL1 and 2).

Unfortunately there is quite a lot of work to getting your example behaving 'correctly' (eg how it looks on ShaderToy), as you need to implement all of the uniforms. In order to get something showing at _all_ using your temporary uniforms, you can do the following:

 - Either convert the shaders to 300 es type for WebGL 2 (eg adding ```#version 300 es``` on the first line, or force WebGL 1 by passing in ```{webgl: 1}``` in the Renderer declaration.
 - Move the line ```float k=7.0+3.0*sin(iGlobalTime*0.15);``` into a function (you can't create dynamic variables in global scope).
 - Add ```iResolution``` as a uniform.
 - Remove the ```vUv``` varying, and change the second argument in the ```mainImage()``` method call to ```gl_FragCoord.xy```

**Comment by Jones-S** [comment]
Hey @gordonnl Thank you a lot. Unfortunately I am pretty busy now and have not found any time to have a look at it. I will as soon as I can free up some time.
Anyway thank you very much for taking your time and helping me out.
Cheers
