### ISSUE TITLE
Color Object

### ISSUE THREAD

**Issue by sketchpunk** [oframe/ogl#41]
Looking around your source and saw a TODO for color. I wrote this recently, thought it might give you something to work from if you want to support various formats from RGB and RGBA. Its crazy simple.

https://gist.github.com/sketchpunk/d710cd486cf9f9c6f9c8f212e38296b1

EDIT:

I took your color object and rewrote it for funs. I saved it to the same gist but as another file called color_webgl. I included the short hand form #fff since you where doing that. I also changed it to a Float32Array but you can always change it back to a regular array. 

All the new forms you can use.
console.log( new Color()  );                    // Test Blank
console.log( new Color( 0xff00ff )  );          // Test Number form
console.log( new Color( 100, "200", 300 )  );   // Test RGB, String and Overflow
console.log( new Color( "#f50" )  );            // Test Short Hand Hex
console.log( new Color( "#ff00ff" )  );         // Test Hex
console.log( new Color( "red" ) );              // Test Color Names
console.log( new Color( "w00t" ) );             // Test Unknown Color name

**Comment by gordonnl** [comment]
Thanks a lot mate! You're a champ. I've just pushed a commit with these updates d6f3fef. Only minor change was choosing decimal values over 8-bit - partly personal preference, and partly as it mimics the GLSL equivalent, allowing to copy/paste if you want to abstract or hard-code some color values.

Interesting note on the Float32Array vs Array extension - I originally had all of the math classes using Float32Array, however it was brought to my attention (by kickass dev @dekdevy)  that it was performing significantly slower due to the extra time in generation. Float32Array gains seem to only be prevalent with larger buffers. Around the same time, the lead developer behind PlayCanvas made a similar discovery, and converted all of their internal math classes to using Array too! I thought that was pretty interesting, not what I would have guessed.

**Comment by sketchpunk** [comment]
Cool Cool

In the beginning of putting together the math lib for fungi, there was an instance or two that I was getting NaN errors because the numbers somehow got turned into a string at some point. Those sometimes can be tricky to debug. So I switched over the Float32Array for type safety. I've read about the performance issue with TypeArrays a long time ago, but its only noticeable in math heavy applications. I built some tests and if I tried to do over 10k allocations between Array vs Float32Array i saw performance really start to dip, when I got to 10 million... Oh boy, did Float32Arrays performed HORRIBLY. Guess what, create an Object Pool for Vec3s and use that in the 10 million test, now they perform almost as good as regular arrays, PLUS the bonus of not getting any spikes from the garbage collector. 

So moral of the story is, If you use them correctly, you'll get good performance, type safety and less garbage collector slow downs :) 

Plus, I'm hoping that Google will take some time at some point to optimize ArrayBuffers. Its kind of silly that a static array takes longer to setup then a Dynamic Array of Variants.
