### ISSUE TITLE
add mouse events on 3D objects (meshes and primitives)

### ISSUE THREAD

**Issue by gregja** [oframe/ogl#67]
Hi,
Do you plan to add a mouse event manager (and eventually a touch event manager) to OGL, for linking that sort of events to 3D objects (meshes and primitives) ?
Thank's a lot

**Comment by gordonnl** [comment]
Hey, no nothing like an input manager is in the plans currently. 

Ideally, OGL should focus on the task of WebGL, and not other application tasks (input management, audio, asset loading etc). I was more-or-less forced to include Loaders for GLTF and textures in order to support GLTF, as there was no other way to achieve it.

For an example of mouse/touch input handling, you could use the [Mouse Flowmap example](https://github.com/oframe/ogl/blob/master/examples/mouse-flowmap.html), though this is probably not the ideal method, depending on your application.

For "linking that sort of events to 3D objects" you can check the [Raycasting example](https://github.com/oframe/ogl/blob/master/examples/raycasting.html), to see how to cast a ray and find what objects are intersected with.

**Comment by gregja** [comment]
Hi @gordonnl 
Thank's a lot for your help. I realize that the raycasting example is closed to my need. I'm going to code some experiments with it, that's cool :). 
If you have some time, you can have a look to this github repo where I code some expperiments with OGL. 
https://github.com/gregja/oglXperiments
I'm a newbie in WebGL and it's a big pleasure for me to code 3D graphism with OGL. 
Thank's a lot for this great project.
