### ISSUE TITLE
Update Position on meshes on Resize

### ISSUE THREAD

**Issue by PierreMouchan** [oframe/ogl#68]
I was wondering if OGL provide any function or method to update my meshes' position outside of the RAF function ? Thanks.

**Comment by gordonnl** [comment]
Hey,
I'm not sure if I understand what you mean, but the `Mesh` class is an extension of `Transform`, which contains properties for `position`, `scale` and `rotation`, so you can do something like the following at any time:
```
const mesh = new Mesh(gl, { geometry, program });
mesh.position.set(-1, 2.2, 10.3);
mesh.rotation.y += 0.1;
```

If, by 'outside of the RAF function' you mean that you're not *seeing* updates, it's because the scene needs to render the updates to the canvas, and in the examples `renderer.render()` is called inside an RAF. If you don't need to render every frame, you can instead call that method whenever you like.

**Comment by PierreMouchan** [comment]
Thanks for the quick answer, by 'outside of the RAF function', i mean i got my main RAF function running (setting mesh.position and mesh.scale is correctly working inside) but when i want to set my meshes' position manually outside of the RAF like `mesh.position.set(x,y,z)`, i'm not seeing the update.

The more I think about it, the more I think it's coming from my lack of webgl knowledges, sorry.
(Currently trying to replicate the curtainjs library with OGL (because it's lighter 👋), btw thank for the  library, i will look through some documentation to find a solution to my problem !)

**Comment by gordonnl** [comment]
No worries!
If you'd like to create a CodeSandbox I can have a look, otherwise good luck ;)

**Comment by PierreMouchan** [comment]
My bad ! 
It was my fault !
I was trying the update the camera aspect and fov with `camera.fov = myNewFOV` and `camera.aspect = myNewAspect` on window resize

Instead i had to use `camera.perspective({aspect: myNewAspect, fov: myNewFOV})` !
