### ISSUE TITLE
undefined skeleton /w GLTF loader

### ISSUE THREAD

**Issue by DougLilliequist** [oframe/ogl#69]
Heya!

So I exported a skinned mesh from blender and noticed that my skeleton is undefined, resulting in an error that says it can't find the skeletons world matrix. Tested the rig in THREE's web editor and it appears to be working. Is there any settings that should be considered when exporting skinned meshes for use with OGL?

![Screenshot (70)_LI](https://user-images.githubusercontent.com/24439812/82666999-ab5b9500-9c3f-11ea-8246-718e373565ab.jpg)

**edit**

Attaching a screen of my blender setup with my rigged mesh. If requested, I can send the blender project.

![Screenshot (71)](https://user-images.githubusercontent.com/24439812/82675927-33489b80-9c4e-11ea-93c3-56a19c181aaf.png)

**Comment by gordonnl** [comment]
Hey,

Yeah that might be handy if you could send me the gltf file (can be glb)!

I can see [in the spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skin) that Skin's skeleton index is optional, however I'm currently not treating it as such - so that's where your error is coming from.
I wonder if just commenting out [this line](https://github.com/oframe/ogl/blob/master/src/extras/GLTFLoader.js#L642) will solve your issues.

`skin.skeleton = nodes[skin.skeleton];`

I can have a closer look though with your file!

Cheers

**Comment by DougLilliequist** [comment]
Cheers! I got it working by commenting out both the line you mentioned and not using the skeleton's world matrix! Will send the .gltf file in case it helps with further development on the GLTFSkin class!

`        this.worldMatrix = this.skeleton.skeleton.worldMatrix;
`

**Comment by gordonnl** [comment]
Thanks mate, I've added that fix.
I'll need to look into a few more GLTF skin animation examples, they're just a bit hard to find actually.
I'm wondering if there are cases where not updating the `worldMatrix` is incorrect, and how else I can determine the skin's root...
