### ISSUE TITLE
Safari Flowmap performance issue

### ISSUE THREAD

**Issue by matthewattanasio** [oframe/ogl#75]
It seems that on the latest version of Safari OSX the flowmap example which can be found [here](https://oframe.github.io/ogl/examples/?src=mouse-flowmap.html) causes the overall machine performance to degrade to almost an unusable state, obviously a frame rate issue. 

Is this a known issue with Safari?

**Comment by gordonnl** [comment]
I'm also just noticing a bizarre issue with safari for that example, however it's not a frame-rate issue. In fact if I open the dev console it starts working perfectly again.

The issue I'm seeing is that it seems many of the input `mousemove` events are not being triggered, so that I only get one every second or so. Does that sound like what you're experiencing?

**Comment by gordonnl** [comment]
Clicking+dragging also solves the issue. It just seems Safari is throttling the mouse move events on that example for some reason. In contrast, the [Post Fluid Distortion Example](https://oframe.github.io/ogl/examples/?src=post-fluid-distortion.html), which uses a very similar `mousemove` event listener doesn't seem to be affected.

**Comment by matthewattanasio** [comment]
yeah, I can replicate that on my end as well.

However, with this flowmap approach, I have repurposed [the codedrop flowmap example](https://tympanus.net/codrops/2019/09/25/mouse-flowmap-deformation-with-ogl/)  and using it on my site https://new-blob--skyfoundry.netlify.app/, however it seems to be causing major performance issues where the whole computer seems to start locking up. 

No other browser causes this issue on my mac. only latest version of safari, any ideas to what it could be?

**Comment by gordonnl** [comment]
I don't think I have the very latest Safari (am on 13.1) but I'm seeing the same issue with the throttled `mousemove` events, however if I scroll etc the site is still running smoothly. Can you explain what you mean by 'locking up'?

**Comment by matthewattanasio** [comment]
Yep, I am running 13.1 as well. Apologies for not being clear. When I mean lockup. I mean the following performance issues are experienced. Then can be experienced when navigating to a new page and then back to the home page. 

- Typing on the keyboard is slow to respond on screen, this is experienced on all programs open, not just safari.
- Scrolling performance, safari and all other programs

It's the same kind of experience when a computers CPU is maxing out. I have a pretty decent MacBook pro. So If it can't run on mine then I am sure many other computers would experience this as well. 

I am using gridsome a Vue static site builder, should I be destroying the OGL instance before leaving the page? Is there a proper way to do so?

**Comment by gordonnl** [comment]
Ah I see. Yes you're right, for me it's super snappy when you first load, but after going to another page and back to the home I start to see issues.

It does seem like perhaps multiple scenes are being instantiated and rendering at once. You could start by just making sure the previous scene stops rendering when leaving (throw a console log in the render loop).

I'm no Vue expert, but you might be able to use something like `keep-alive` - https://vuejs.org/v2/guide/migration.html#keep-alive-Attribute-replaced - as a way to avoid re-creating the scene every time users return to the page. I'd try to do something like that - pause rendering, and just un-append the canvas when the user leaves, and resume and re-append when they return.

**Comment by matthewattanasio** [comment]
@gordonnl that's already helped immensely regarding solving the navigation performance issue using keep alive and further modifications to the code. 

Was just wondering if you got any great ideas on solving the first issue which was the input `mousemove` events triggering at a similar rate to other browsers.

**Comment by gordonnl** [comment]
I've never noticed the issue before, but it does definitely seem like an internal Safari bug/feature.
The fact that the issue is evident in the Mouse Flowmap example, but not the Post Fluid Distortion example - even though the exact same event listener is implemented - makes me think it's some performance-gaining feature that Safari has added when a website isn't consuming many resources.
Because the issue disappears when the developer console is open, there's nothing I can think of in order to debug it more thoroughly, without resorting to trial and error.
