### ISSUE TITLE
Video texture support

### ISSUE THREAD

**Issue by Hersir88** [oframe/ogl#76]
Hi,
trying to Redner video as texture and found out that its not possible to update texture right now as there are check if image is same it ignores update.

**Comment by Hersir88** [comment]
```typescript
texture.image = null;
texture.update();
texture.image = video;
texture.update();
```

this is my workaround for now, to render

**Comment by gordonnl** [comment]
Hey, the [texture examples](https://oframe.github.io/ogl/examples/?src=textures.html) includes a video texture, and it seems to still be working (on Chrome at least).

For video textures in order to keep updating you need to manually set the `needsUpdate` flag. Here is that relevant chunk of code from the example:
```
// Attach video and/or update texture when video is ready
if (video.readyState >= video.HAVE_ENOUGH_DATA) {
    if (!videoTexture.image) videoTexture.image = video;
    videoTexture.needsUpdate = true;
}
```

**Comment by Hersir88** [comment]
Thanks didn't saw this :)
