### ISSUE TITLE
Suggestion: include color write on and off

### ISSUE THREAD

**Issue by DougLilliequist** [oframe/ogl#86]
Just as you have the ability to determine if you want to write to the depth buffer or not, it would be neat to have the ability to enable and disable writing to the color buffer!

**Comment by gordonnl** [comment]
It's definitely something to discuss. 

Since the beginning I always wanted to avoid just adding wrappers for every single gl command, as I don't want people scared of accessing the native `gl` object. 

You can see these very old comments at the top of `Renderer.js` for example, that mention the `colorMask` command (writing to the color buffer).

https://github.com/oframe/ogl/blob/3120154d4241cb48f27fe1d741ff51c997c4d345/src/core/Renderer.js#L5-L11

So it's indeed possible, but I just don't provide a wrapper through the `Renderer` class. Do you think a wrapper would offer any benefit?

One note is that to avoid _clearing_ the color buffer specifically, a boolean `Renderer.color` exists that you can set to false (color buffer is cleared by default). The reason for storing this is that it's a more complex method, so I simplify it by storing state internally.
https://github.com/oframe/ogl/blob/3120154d4241cb48f27fe1d741ff51c997c4d345/src/core/Renderer.js#L324-L328

**Comment by gordonnl** [comment]
closing this for now. Feel free to re-open if you can think of any added benefit
